blank_issues_enabled: false
contact_links:
  - name: Slack Community Chat
    url: https://github.com/sorokinvld/portal-brandpack/blob/423f16ea2fcd9d4d3400f8e3915dbcf582eaf595/apple-touch-icon.png
    about: Ask questions and discuss with other LiveKit users in real time.
